---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/18/2023 10:39 AM
---

if mods["bobenemies"] then
    table.insert(data.erm_spawn_specs, {
        mod_name = "bob-",
        force_name = FORCE_NAME,
        moisture = 1, -- 1 = Dry and 2 = Wet
        aux = 2, -- 1 = red desert, 2 = sand
        elevation = 2, --1,2,3 (1 low elevation, 2. medium, 3 high elavation)
        temperature = 2, --1,2,3 (1 cold, 2. normal, 3 hot)
    })
end
