---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/23/2021 12:53 PM
---
require("__enemyracemanager__/global")
require('prototypes/finalize-factoriopedia')
require('prototypes/health-balance')

if DEBUG_MODE then
    data.raw["radar"]["radar"]["max_distance_of_sector_revealed"] = 15
    data.raw["radar"]["radar"]["max_distance_of_nearby_sector_revealed"] = 15

    local autoplace_count = 0
    local prototype_count = 0
    local erm_prototype_count = 0
    local damage_types_count = 0
    local damage_types = {}
    for type_name, entity_type in pairs(data.raw) do
        for entity_name, entity in pairs(entity_type) do
            prototype_count = prototype_count + 1

            if entity.autoplace ~= nil then
                autoplace_count = autoplace_count + 1

                local nameToken = util.split(entity.name, "--")
                if table_size(nameToken) == 3 then
                    erm_prototype_count = erm_prototype_count + 1
                end
            end

            if type_name == "damage-type" then
                damage_types_count = damage_types_count + 1
                table.insert(damage_types, entity.name)
            end
        end
    end
    log("Total Prototypes:" .. prototype_count)
    log("Total Prototypes with autoplace: " .. autoplace_count)
    log("Total ERM enemy prototype with autoplace: " .. erm_prototype_count)

    log("Total Damage Types:"..damage_types_count)
    log(serpent.block(damage_types))

end