---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/23/2021 12:53 PM
---

if DEBUG_MODE then
    data.raw["radar"]["radar"]['max_distance_of_sector_revealed'] = 15
    data.raw["radar"]["radar"]['max_distance_of_nearby_sector_revealed'] = 15
end
