---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/1/2023 10:55 PM
---

require('global')

if mods['Krastorio2'] then
    data:extend {
        {
            type = "bool-setting",
            name = "enemyracemanager-vanilla-k2-creep",
            description = "enemyracemanager-vanilla-k2-creep",
            setting_type = "startup",
            default_value = true,
            order = "enemyracemanager-1000",
        }
    }
end