NAUVIS_MIXED = "Mixed Races"
NAUVIS_2_WAY = "2 Way Split"
NAUVIS_4_WAY = "4 Way Split"

QUALITY_CASUAL = "Casual"
QUALITY_NORMAL = "Normal"
QUALITY_ADVANCED = "Advanced"
QUALITY_HARDCORE = "Hardcore"
QUALITY_FIGHTER = "Fighter"
QUALITY_CRUSADER = "Crusader"
QUALITY_THEONE = "The One"


ATTACK_RANGE_14 = 14
ATTACK_RANGE_20 = 20
ATTACK_RANGE_26 = 26
ATTACK_RANGE_32 = 32
ATTACK_RANGE_40 = 40

X_AXIS = "x-axis"
Y_AXIS = "y-axis"

RACE_EMPTY = "empty"

BUILDING_DEFAULT = "Base Game Default"
BUILDING_EXPAND_ON_CMD = "Command Center Expansion"
BUILDING_A_TOWN = "Build A Base"
BUILDING_EXPAND_ON_ARRIVAL = "Full Expansion"

BUILDING_FORMATION_1_1_2 = "1-1-2"
BUILDING_FORMATION_1_2_4 = "1-2-4"
BUILDING_FORMATION_1_3_8 = "1-3-8"
BUILDING_FORMATION_1_4_5 = "1-4-5"
BUILDING_FORMATION_1_4_15 = "1-4-15"
BUILDING_FORMATION_1_6_8 = "1-6-8"
BUILDING_FORMATION_1_8_11 = "1-8-11"
BUILDING_FORMATION_1_9_0 = "1-9-0"
BUILDING_FORMATION_1_9_10 = "1-9-10"
BUILDING_FORMATION_RANDOM = "random"

BOSS_NORMAL = "Normal"
BOSS_HARD = "Advanced"
BOSS_GODLIKE = "Godlike"

BOSS_SPAWN_SQUAD = "Squad"
BOSS_SPAWN_PATROL = "Patrol"
BOSS_SPAWN_PLATOON = "Platoon"

