---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/14/2025 8:43 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/14/2025 8:43 PM
---

local sounds = require("__base__.prototypes.entity.sounds")
local item_sounds = require("__base__.prototypes.item_sounds")
require("util")
local biter_ai_settings = require ("__base__.prototypes.entity.biter-ai-settings")
local ERM_UnitHelper = require('__enemyracemanager__/lib/rig/unit_helper')
local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
local ERM_AnimationRig = require('__enemyracemanager__/lib/rig/animation')
local ERMPlayerUnitHelper = require("__enemyracemanager__/lib/rig/player_unit_helper")
local ArmyEconomyHelper = require('__erm_libs__/prototypes/army_economy_helper')

local distraction_cooldown = 30
local attack_range = ERMPlayerUnitHelper.get_attack_range(1)
local vision_distance = ERMPlayerUnitHelper.get_vision_distance(attack_range)

local laser_drone = util.table.deepcopy(data.raw['unit'][MOD_NAME..'--defender--5'])
local prefix  = "player"
local name = "drone_suicide"
local icons = {
    {
        icon = "__base__/graphics/icons/defender.png",
        icon_size = 64,
    },
}
local resistances = {
    acid = {75},
    poison = {75},
    physical = {75},
    fire = {75},
    explosion = {75},
    laser = {75},
    electric = {75},
    cold = {75}
}

local run_animation = util.table.deepcopy(laser_drone.run_animation)
ERM_UnitTint.apply_runtime_tint(run_animation['layers'][2])


laser_drone.name = prefix.."--controllable--"..name
laser_drone.localised_name = { 'entity-name.'..prefix.."--controllable--"..name}
laser_drone.icons = icons
laser_drone.flags = { "placeable-enemy", "placeable-player", "placeable-off-grid", "not-flammable" }
laser_drone.has_belt_immunity = true
laser_drone.max_health = 100 * ERMPlayerUnitHelper.get_health_multiplier()
laser_drone.order = prefix.."--controllable--"..name
laser_drone.shooting_cursor_size = 2
laser_drone.resistances = ERMPlayerUnitHelper.get_resistances(resistances)
laser_drone.subgroup = "erm_controllable_units"
laser_drone.shooting_cursor_size = 2
laser_drone.can_open_gates = true
laser_drone.map_color = ERM_UnitTint.tint_army_color()
laser_drone.healing_per_tick = 0
laser_drone.vision_distance = vision_distance
laser_drone.movement_speed = 0.3 * ERMPlayerUnitHelper.get_speed_multiplier()
laser_drone.radar_range = 2
laser_drone.distraction_cooldown = distraction_cooldown
laser_drone.run_animation = run_animation
laser_drone.attack_parameters = {
    type = "projectile",
    range_mode = "bounding-box-to-bounding-box",
    ammo_category = "landmine",
    range = 1,
    cooldown = 90,
    cooldown_deviation = 0.2,
    warmup = 15,
    damage_modifier = ERMPlayerUnitHelper.get_damage_multiplier(),
    ammo_type = {
        category = "landmine",
        target_type = "direction",
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                source_effects =
                {
                    {
                        type = "script",
                        effect_id = SELF_DESTRUCT_ATTACK,
                    },
                    {
                        type = "create-entity",
                        entity_name = "erm-fire-explosion-air_normal-1"
                    },
                },
                target_effects = {
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = "not-same",
                            radius = 5,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    {
                                        type = "damage",
                                        damage = { amount = 1200, type = "explosion" },
                                        apply_damage_to_trees = true
                                    },
                                }
                            }
                        }
                    },
                }
            }
        },
    },
    animation = run_animation,
},


data.extend({laser_drone})

ArmyEconomyHelper.create_item({
    prefix = prefix,
    name = name,
    icons = icons,
    subgroup = prefix.."--erm_controllable",
    stack_size = 20,
    weight = 50,
})

ArmyEconomyHelper.create_recipe({
    prefix = prefix,
    name = name,
    energy_required = 30,
    ingredients =
    {
        {type = "item", name = "flying-robot-frame", amount = 4},
        {type = "item", name = "low-density-structure", amount = 8},
        {type = "item", name = "accumulator", amount = 6},
        {type = "item", name = "explosives", amount = 12},
    },
    category = prefix.."--erm_controllable",
    amount = 1
})

ArmyEconomyHelper.create_deploy_recipe({
    prefix = prefix,
    name = name,
    icons = util.table.deepcopy(icons),
    category = prefix.."--erm_controllable",
})

table.insert(data.raw['technology']['robotics']['effects'],         {
    type = "unlock-recipe",
    recipe = prefix.."--controllable--"..name
})