---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2024 7:01 PM
---

local simulations = require("__enemyracemanager__/prototypes/tips-and-tricks/simulations")

data:extend(
    {
        {
            type = "tips-and-tricks-item-category",
            name = "enemyracemanager",
            order = "b-[enemyracemanager]"
        },
        {
            type = "tips-and-tricks-item",
            name = "enemyracemanager-general-info",
            category = "enemyracemanager",
            order = "a",
            is_title = true,
            trigger =
            {
                type = "or",
                triggers =
                {
                    {
                        type = "shoot",
                        target = "enemy"
                    },
                    {
                        type = "shoot",
                        target = "entity"
                    },
                    {
                        type = "time-elapsed",
                        ticks = 5 * second
                    }
                }
            },
            simulation = simulations.general
        },
        {
            type = "tips-and-tricks-item",
            name = "enemyracemanager-quality-system",
            category = "enemyracemanager",
            order = "a",
            indent = 1,
            trigger =
            {
                type = "or",
                triggers =
                {
                    {
                        type = "shoot",
                        target = "enemy"
                    },
                    {
                        type = "shoot",
                        target = "entity"
                    },
                    {
                        type = "time-elapsed",
                        ticks = 5 * second
                    }
                }
            },
            simulation = simulations.quality_system
        },
    }
)