---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/6/2024 9:30 AM
---

local entity_name_token = {
    'gleba-spawner',
    'wriggler-pentapod',
    'strafer-pentapod',
    'stomper-pentapod',
}

local force = game.forces[GLEBA_FORCE_NAME]
if not force then
    force = game.create_force(GLEBA_FORCE_NAME)
end

local gleba = 'gleba'
local enemy_force = game.forces[FORCE_NAME]
if game.surfaces[gleba] then
    force.set_evolution_factor(enemy_force.get_evolution_factor(gleba), gleba)
    force.set_evolution_factor_by_pollution(enemy_force.get_evolution_factor_by_pollution(gleba), gleba)
    force.set_evolution_factor_by_time(enemy_force.get_evolution_factor_by_time(gleba), gleba)
    force.set_evolution_factor_by_killing_spawners(enemy_force.get_evolution_factor_by_killing_spawners(gleba), gleba)
end

--- Change enemy force on gleba
for _, surface in pairs(game.surfaces) do
    local entities = surface.find_entities_filtered({
        type={'unit-spawner','spider-unit','unit'},
        force='enemy'
    })
    for _, entity in pairs(entities) do
        for _, name in pairs(entity_name_token) do
            if string.find(entity.name,name,nil,true) then
                entity.force = GLEBA_FORCE_NAME
            end
        end
    end
end 