---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 1/2/2021 4:48 PM
---

local ERM_MainWindow = require('__enemyracemanager__/gui/main_window')
local ERM_DetailWindow = require('__enemyracemanager__/gui/detail_window')
local ERM_BossVictoryDialog = require('__enemyracemanager__/gui/victory_dialog')
local ERM_BossDetailWindow = require('__enemyracemanager__/gui/boss_detail_window')
local ERM_ArmyControlWindow = require('__enemyracemanager__/gui/army_control_window')

local ERM_GUI = {
    main_window = ERM_MainWindow,
    detail_window = ERM_DetailWindow,
    victory_dialog = ERM_BossVictoryDialog,
    boss_detail_window = ERM_BossDetailWindow,

    army_control_window = ERM_ArmyControlWindow
}

return ERM_GUI