---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/16/2024 1:46 AM
---

local SharedFunctions = {}

function SharedFunctions.add_mini_map(pane, name, player, entity, position, zoom, style, tooltip)
    zoom = zoom or 0.75
    position = position or entity.position
    local map = pane.add {
        type = 'minimap',
        name = name,
        force = entity.force.name,
        chart_player_index = player.index,
        surface_index = entity.surface.index,
        position = position,
        zoom = zoom,
        tooltip = tooltip or nil
    }
    for key, value in pairs(style) do
        map.style[key] = value
    end
end

return SharedFunctions