---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2025 4:51 PM
---

local radar = util.table.deepcopy(data.raw['radar']['radar'])

radar.name = 'erm-air-raid-radar'
radar.order = 'd[radar]-b[erm-air-raid-radar]'
radar.energy_per_sector = "10MJ"
radar.max_distance_of_sector_revealed = 1
radar.max_distance_of_nearby_sector_revealed = 1
radar.energy_per_nearby_scan = "5.57MJ"
radar.energy_usage = "1MW"
radar.minable = {mining_time = 0.1, result = "erm-air-raid-radar"}
radar.is_military_target = true
radar.max_health = 2000
radar.connects_to_other_radars = false

local radar_item = util.table.deepcopy(data.raw['item']['radar'])

radar_item.name = 'erm-air-raid-radar'
radar_item.order = 'd[radar]-b[erm-air-raid-radar]'
radar_item.place_result = "erm-air-raid-radar"

local radar_recipe = util.table.deepcopy(data.raw['recipe']['radar'])

radar_recipe.name = 'erm-air-raid-radar'
radar_recipe.order = 'd[radar]-b[erm-air-raid-radar]'
radar_recipe.ingredients =
{
    {type = "item", name = "advanced-circuit", amount = 20},
    {type = "item", name = "iron-gear-wheel", amount = 5},
    {type = "item", name = "iron-plate", amount = 20},
    {type = "item", name = "steel-plate", amount = 10}
}
radar_recipe.results = {{type="item", name="erm-air-raid-radar", amount=1}}

data.extend({
    radar,
    radar_item,
    radar_recipe,
})

local technology = data.raw['technology']['radar']

table.insert(technology.effects, {
    type = "unlock-recipe",
    recipe = "erm-air-raid-radar"
})

