---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/19/2024 8:22 PM
---

local invisible_unit = "invisible-unit"

for _, turret in pairs(data.raw["ammo-turret"]) do
    if type(turret["ignore_target_mask"]) == "table" then
        table.insert(turret["ignore_target_mask"], invisible_unit)
    else
        turret["ignore_target_mask"] = { invisible_unit }
    end
end

for _, turret in pairs(data.raw["turret"]) do
    if type(turret["ignore_target_mask"]) == "table" then
        table.insert(turret["ignore_target_mask"], invisible_unit)
    else
        turret["ignore_target_mask"] = { invisible_unit }
    end
end

for _, turret in pairs(data.raw["fluid-turret"]) do
    if type(turret["ignore_target_mask"]) == "table" then
        table.insert(turret["ignore_target_mask"], invisible_unit)
    else
        turret["ignore_target_mask"] = { invisible_unit }
    end
end

--- Includes all electric turrets
for _, turret in pairs(data.raw["electric-turret"]) do
    if type(turret["attack_target_mask"]) == "table" then
        table.insert(turret["attack_target_mask"], invisible_unit)
    else
        turret["attack_target_mask"] = { "common", "ground-unit", "flying", invisible_unit }
    end
end

--- Apply invisible trigger_target_mask to invis_ prefix units
for _, entity in pairs(data.raw["unit"]) do
    if string.find(entity.name, "invis_", 1, true) then
        entity.trigger_target_mask = {invisible_unit}
    end
end
