---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/30/2024 1:55 PM
---

local include_types = {
    'transport-belt',
    "underground-belt",
    "splitter",
    "mining-drill",
    "lab",
    "inserter",
    "pipe",
    "pipe-to-ground",
    "container",
    "electric-pole",
    "furnace",
    "assembling-machine",
    "radar",
    "pump",
    "roboport",
    "storage-tank",
    "straight-rail",
    "curved-rail-a",
    "curved-rail-b",
    "half-diagonal-rail",
    "elevated-curved-rail-a",
    "elevated-curved-rail-b",
    "elevated-half-diagonal-rail",
    "elevated-straight-rail",
    "rail-chain-signal",
    "rail-signal",
    "loader-1x1",
    "loader",
    "lightning-attractor",
    "agricultural-tower"
}


for _, type in pairs(include_types) do
    if data.raw[type] then
        for _, entity in pairs(data.raw[type]) do

            if entity.max_health and (entity.type == "container" or entity.type == "logistic-container") then
                entity.max_health = math.max(entity.max_health * 2.5, 500)
            elseif entity.max_health and entity.max_health < 500 then
                entity.max_health = math.max(entity.max_health * 2, 500)
            end
        end
    end
end