---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/1/2024 4:56 PM
---

data:extend({
    { -- Falling meteor projectiles
        type = "projectile",
        name = 'erm-test-meteor',
        acceleration = 0,
        rotatable = false,
        pictures =
        {
            {
                filename = "__base__/graphics/decorative/rock-big/rock-big-01.png",
                width = 94,
                height = 64,
                shift = {-0.046875, 0.171875},
                hr_version =
                {
                    filename = "__base__/graphics/decorative/rock-big/hr-rock-big-01.png",
                    width = 188,
                    height = 127,
                    scale = 0.5,
                    shift = {-0.046875, 0.171875}
                }
            },
        },
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "script",
                        effect_id = ENVIRONMENTAL_ATTACK
                    }
                },
            },
        },
        flags = { "not-on-map" },
    },
})