---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 3/31/2021 8:54 PM
---
--- @deprecated
---

require('util')

local BaseBuildProcessor = {}

function BaseBuildProcessor.create_build_group(group, limit)
    if not (group and group.valid) then
        return
    end
    limit = limit or 12
    local members = {}
    for _, unit in pairs(group.members) do
        members[#members + 1] = unit
    end
    local new_group = group.surface.create_unit_group {position=group.position ,force=group.force}
    for idx = 1, math.min(limit, #members) do
        local unit = members[idx]
        if unit and unit.valid then
            new_group.add_member(unit)
        end
    end

    new_group.set_command({
        type = defines.command.build_base,
        destination = group.position,
        distraction = defines.distraction.by_damage
    })
end

return BaseBuildProcessor