---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/25/2022 12:58 AM
---

local BossAttackProcessor = require("__enemyracemanager__/lib/boss_attack_processor")


--- Punish player when they can"t beat boss within the time limit.
--- Launch X amount of super attacks at various targetable places

local BossDespawnProcessor = {}

function BossDespawnProcessor.exec()
    BossAttackProcessor.process_despawn_attack()
end

return BossDespawnProcessor