---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/16/2022 2:58 PM
---

require('__stdlib__/stdlib/utils/defines/time')

local ErmConfig = require('__enemyracemanager__/lib/global_config')
local ErmForceHelper = require('__enemyracemanager__/lib/helper/force_helper')
local ErmRaceSettingsHelper = require('__enemyracemanager__/lib/helper/race_settings_helper')
local ErmAttackGroupChunkProcessor = require('__enemyracemanager__/lib/attack_group_chunk_processor')
local ErmSurfaceProcessor = require('__enemyracemanager__/lib/surface_processor')

local ErmDebugHelper = require('__enemyracemanager__/lib/debug_helper')

local BossAttackProcessor = {}

local attackable_entities_cache = nil
local attackable_entities_cache_size = 0

local pick_near_by_player_entity_position = function()
    if attackable_entities_cache == nil then
        local surface = global.boss.surface
        attackable_entities_cache = surface.find_entities_filtered {
            force = ErmForceHelper.get_player_forces(),
            radius = 64,
            position = global.boss.entity_position,
            limit = 50
        }
        attackable_entities_cache_size = #attackable_entities_cache
    end
    return attackable_entities_cache[math.random(1,attackable_entities_cache_size)].position
end

function BossAttackProcessor.unset_attackable_entities_cache()
    attackable_entities_cache = nil
    attackable_entities_cache_size = 0
end

function BossAttackProcessor.exec_basic()
    local surface = global.boss.surface
    local position = pick_near_by_player_entity_position()
    surface.create_entity({
        name = "erm-energy-explosion-blue-1",
        position = position
    })
end

function BossAttackProcessor.exec_advanced()
    local surface = global.boss.surface
    local position = pick_near_by_player_entity_position()
    surface.create_entity({
        name = "erm-energy-explosion-green-1",
        position = position
    } )
end

function BossAttackProcessor.exec_super()
    local surface = global.boss.surface
    local position = pick_near_by_player_entity_position()
    surface.create_entity({
        name = "erm-ball-explosion-fire-2",
        position = position
    } )
end


return BossAttackProcessor