---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/27/2021 5:22 PM
---
local String = require('__stdlib__/stdlib/utils/string')

local ErmConfig = require('lib/global_config')
local ErmForceHelper = require('lib/helper/force_helper')
local ErmLevelProcessor = require('__enemyracemanager__/lib/level_processor')

local CommandProcessor = {}

local is_not_from_admin = function(command)
    local player = game.get_player(command.player_index)
    if (not player.admin) then
        game.print({'description.command-error-permission'})
        return true
    end

    return false
end

return CommandProcessor