---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 3/16/2021 9:33 PM
---
local version = require("__erm_libs__/stdlib/version")

if mods["ArmouredBiters"] then
    require "ArmouredBiters/biter"
    require "ArmouredBiters/spawner"
end

if mods["Cold_biters"] then
    require "Cold_Biters/biter"
    require "Cold_Biters/spawner"
    require "Cold_Biters/worm"
end

if mods["Explosive_biters"] then
    require "Explosive_Biters/biter"
    require "Explosive_Biters/spawner"
    require "Explosive_Biters/worm"
end

if mods["Toxic_biters"] then
    require "Toxic_Biters/biter"
    require "Toxic_Biters/spawner"
    require "Toxic_Biters/worm"
end

require "shared/resistance"