---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/6/2023 12:47 PM
---
local version = require('__stdlib__/stdlib/vendor/version')
require('global')

if mods['Krastorio2'] then
    require 'K2/settings'
end

if mods['ArmouredBiters'] then
    require 'ArmouredBiters/settings'
end

if mods['Cold_biters'] then
    require 'Cold_Biters/settings'
end

if mods['Explosive_biters'] then
    require 'Explosive_Biters/settings'
end

if mods['Toxic_biters'] then
    require 'Toxic_Biters/settings'
end