---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/1/2021 8:29 PM
---
local GlobalConfig = require("__enemyracemanager__/lib/global_config")
local PlayerUnitHelper = {}

local RATIO = 0.5

function PlayerUnitHelper.get_health_multiplier()
    return math.max((10 + ((settings.startup["enemyracemanager-max-hitpoint-multipliers"].value - 20) * (RATIO + 0.3))), 10)
end

function PlayerUnitHelper.get_speed_multiplier()
    return math.max(1 + ((settings.startup["enemyracemanager-running-speed-multipliers"].value - 1) * RATIO), 1)
end

function PlayerUnitHelper.get_damage_multiplier()
    return math.max(1 + ((settings.startup["enemyracemanager-damage-multipliers"].value - 1) * (RATIO + 0.5)), 1)
end

function PlayerUnitHelper.get_attack_range(ratio, value)
    ratio = ratio or 1
    value = value or 0
    return math.floor(GlobalConfig.get_max_attack_range() * ratio) + value
end

function PlayerUnitHelper.get_vision_distance(attack_range)
    if (attack_range <= 24) then
        return 32
    end

    return attack_range + 8
end

function PlayerUnitHelper.get_resistances(resistances)
    local formatted_resistances = {}
    for name, values in pairs(resistances) do
        local resistance = {}
        resistance.type = name
        if not values[1] then
            error(name..' is missing a percentage value')    
        end
        resistance.percent = values[1]
        if values[2] then
            resistance.decrease = values[2]
        end
        
        table.insert(formatted_resistances, resistance)
    end
    
    return formatted_resistances
end

return PlayerUnitHelper