---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/23/2020 8:27 PM
---

local String = require('__stdlib__/stdlib/utils/string')
local Math = require('__stdlib__/stdlib/utils/math')
local Table = require('__stdlib__/stdlib/utils/table')

local ForceHelper = require('__enemyracemanager__/lib/helper/force_helper')
local CustomAttackHelper = require('__enemyracemanager__/lib/helper/custom_attack_helper')

local CustomAttacks = {}

CustomAttacks.valid = CustomAttackHelper.valid

function CustomAttacks.process_logistic(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'droppable_units'))
end

function CustomAttacks.process_constructor(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'construction_buildings'))
    event.source_entity.die('neutral')
end

return CustomAttacks